services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      #- REDIS_URL=redis://redis:6379/0
        REDIS_URL: redis://redis:6379/0
        BACKEND_PORT: 8000
    
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    environment:
        #- REDIS_URL=redis://redis:6379/0
        REDIS_URL: redis://redis:6379/0
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment: #added
      API_BASE: http://backend:8000


  


